POST /register HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
  "username": "Himanshu",
  "password": "12345678",
  "email": "himanshu@gmail.com",
  "name": "himanshu"
}

###
POST /login HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
  "email": "himanshu@gmail.com",
  "password": "12345678"
}


###
GET http://localhost:9000/get_user_and_profile
Content-Type: application/json

{
    "token": 
}