POST http://localhost:9000/register HTTP/1.1
Content-Type: application/json
{
    "username"
    "password"
    "email"
    "name"
}

###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json
{
    "email"
    "password"
}

###
GET http://localhost:9000/get_user_and_profile
Content-Type: application/json

{
    "token": 
}